### ISSUE TITLE
The count attribute doesn't seem to display lines for me.

### ISSUE THREAD

**Issue by TNT-c** [cesarParra/lightning-stencil#28]
`<c-stencil height="600" weight-variant="medium" count="10"></c-stencil>`
![image](https://github.com/cesarParra/lightning-stencil/assets/18352383/90d6bfe0-28fe-43a2-8c65-60966472ac63)

**Comment by cesarParra** [comment]
@TNT-c The height is per individual row, so if you want 10 lines spanning a total height of 600px you will need to specify a count of 10 but a height of 60px each.

```
<c-stencil height="60" weight-variant="medium" count="10"></c-stencil>
````

![Kapture 2024-03-29 at 07 45 28](https://github.com/cesarParra/lightning-stencil/assets/2524257/7a95959b-30fe-4c76-b0ac-c49939235977)

**Comment by TNT-c** [comment]
Got it. Thank you for following up!
